---
swagger: "2.0"
info:
  description: "Just testing"
  version: "1.0.0"
  title: "Greetings API"
host: "localhost:8080"
basePath: "/v1"
schemes:
- "http"
produces:
- "application/json"
paths:
  /greetings:
    get:
      summary: "Product Types"
      description: "The Products endpoint returns information about the *Uber* products\n\
        offered at a given location. The response includes the display name\nand other\
        \ details about each product, and lists the products in the\nproper display\
        \ order.\n"
      operationId: "greetingsGET"
      parameters:
      - name: "name"
        in: "query"
        description: "Name to greet"
        required: false
        type: "string"
        format: "string"
      responses:
        200:
          description: "Greeting"
          schema:
            type: "object"
            properties: {}
      x-swagger-router-controller: "Default"
definitions:
  GreetingResponse:
    type: "object"
    properties:
      creation:
        type: "string"
        format: "date-time"
        description: "Creation date"
      message:
        type: "string"
        format: "string"
        description: "Message"
