sudo: required
language: node_js
node_js:
- '6.5'
services:
- docker
script:
  - npm install && npm test && npm test:export-coverage
  - docker build -t mag3io/sb-greetings .
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push mag3io/sb-greetings; fi
env:
  global:
  - secure: cVrKAH9/vNnMXsOH2dNjo6J6IjKpD5Sq+wPe02xPovzCcdkE7R1OGyJF5elpMcXzS1QyD9E75Lo2CKdHuBYywxUEYu2vfxTMbycs/LC3w3ITpPOg2miG5brW+rS6PKVUkPTWNxGX4py3W5oLd+iAJGHmaE0YzzcTjd8wQol3o5q7XQLk4J5CDVHoIJ91KVRNGStVIzivbCuYK2AC8H8c6chUU++u4OW93rqBpbW9vZO0Ops8FT5HgXUNHB3kzu7klE3hAgGsXoXWW5dsnSHhAIP9SIF1kvYONq0boHCKaogD4QxUTGriSh35HF9yXFRCdyE9FDHAMqa+IhCY06EoPGDP2ZhnABG501ih4ThgMj72pNiccTsSyWK1f0L/ER/FlftpvRXWINyBSvIbul+PPPO/l2gH7ujratXYNcZUiJfn3h2eS0XPIkKxejpReZBFSMV6bRX5ppOcX2IU4TXgcWf/3wedmImFBqMStcoQpTZvD5Fbcf/xPmbbVOoDNZHO8T6DnYojhK3w76jHL89BBq4slB1zk11Jkl3jMU15OurOuh/iiOCQZug8Mg6uqXJli7PwarpH8FZpc1ykyxk3raoRXZ8acRsl4Yz2+mJQ0tgbjyXw9tQj8cm9iFrd7Hivtn/RJ5wHdcyrmTWCpH0uDwkiEFxtfdE44SMDRI8LI9s=
  - secure: Q4OlayDTt6kZ26+CMbRGy9fCwtVpMkc2Bbos8UXkRhZ/vdVJ7L1VJ0lXdC3rThCaxEW269fedrtSQCOeEhIorOktcj6EDDGuNq3ogKaHYgdY/TlvjiKTjjapRO6CNysPrpdrcpqhFZ+cNilZUD8bBkx3UdTdVHmbhfwsNYsilkpP4P1u+E7Pbi0TsfUJxDXsOAZEcoCijfk2f0A+JrStd0tA0LVBB5QUgeLomxaZocLrDO1Zoc5A6iwfL3aDq3jGBXJeMRlYB7wIq1bClm5v8H8snLcBkVo8XrJmpPa7XcfwOzsAtwjELlzKvLeKNyhwvLbHOFElqPlMedWq8/p7BbOUiuEHB7iVVpSjmVZL3IJfKxDNXS841nNaCBtNXk6Ecy2IHtW+p+HHYfPk5GowpOwkwOHlM5vwzXb+DN1FnUVPGE6JlzHeS1O6TpzlBERUdfx0ZhA3aS+0XWyv3XipFWxYyZyiI5N4q9D+kwSsDzd8IYkXGMVNWhevLvLTfAJCl0w/gsZ12PKMk3NqZ98TF3KTL9c8xE+j+ynQc/4jdqu+fPsY9n56M87N3ewamzZIqIkPTkW1BPpHDkGVigRCahH7E4XEA7V6bMVTi3wX26zdBf7DkNdhwERKchgKqW36rcQkYBiCAdAMYL3Gg+e3NnoodiIHXgSLt25TakWfftA=
