version: "2.0"

#### Services ####
services:
  sb-greetings:
    image: mag3io/sb-greetings
    logging:
      driver: fluentd
      options:
 #       fluentd-address: localhost:24224
        fluentd-tag: docker.{{.FullID}}
    ports:
      - '3000:3000'
    networks:
      - logging
#    external_links:
#      - efk_fluentd_1:fluentd

### Networks ###
networks:
  logging:
    external:
      name: logging